"""
NIH activity codes and their official names, copied from NIH's published list.

Why this is a data file and not a table typed by hand: the card prints the agency's
code beside LabMatch's plain wording ("Training program", "Career award"), and Details
prints NIH's own name for the code. The phase 3 spec's first kind table was written
from memory and a critic found it wrong in places (R00 is NIH's "Research Transition
Award", not a career award). A name shown as NIH's has to be NIH's, so every string
below is the "Title" cell of NIH's table, as published.

Source:    https://grants.nih.gov/funding/activity-codes
           (https://grants.nih.gov/grants/funding/ac_search_results.htm redirects there)
Retrieved: 2026-09-28, ONE GET request, the whole table on one page: 258 rows, 258
           distinct codes, columns "Activity Code", "Funding Category", "Title",
           "Description".

What was done to the text: HTML tags removed, entities unescaped, leading and trailing
whitespace trimmed (PF5 ends in a non-breaking space on the page). Nothing else: no
re-casing, no spelling fixes. NIH's typographic apostrophes and double hyphens are kept
("NIH Director’s Pioneer Award (NDPA)", "Research Project--Cooperative Agreements"),
and so are the doubled spaces inside the names of U44, U86, U87, which a browser collapses
when it renders them.

Known limits, stated rather than papered over:
- This is a snapshot. NIH adds and retires codes; a code RePORTER returns that is not
  here gets official_name() None and the card shows no tag (contract 3.4, "unknown").
  It is never guessed from the letter prefix.
- The names are terse and sometimes opaque ("Exploratory Grants" for P20). That is why
  the plain tag wording lives in award_kinds.py and is labelled LabMatch's.
- NIH's "Funding Category" column is kept in FUNDING_CATEGORY for whoever reviews the
  kind table. 92 of the 258 codes have a blank category on NIH's page and are absent
  from that dict.

Pure data: no network, no database, no import from the rest of the backend.
"""
from typing import Dict, Optional

SOURCE_URL = "https://grants.nih.gov/funding/activity-codes"
RETRIEVED_ON = "2026-09-28"

# code -> NIH's "Title" cell, verbatim. Order is NIH's (alphabetical by code).
OFFICIAL_NAMES: Dict[str, str] = {
    "C06": "Research Facilities Construction Grant",
    "D43": "International Research Training Grants",
    "D71": "International Research Training Planning Grant",
    "DP1": "NIH Director’s Pioneer Award (NDPA)",
    "DP2": "NIH Director’s New Innovator Awards",
    "DP3": "Type 1 Diabetes Targeted Research Award",
    "DP4": "NIH Director’s Pathfinder Award - Multi-Yr Funding",
    "DP5": "Early Independence Award",
    "DP7": "NIH Director’s Workforce Innovation Award",
    "E11": "Grants for Public Health Special Projects",
    "F05": "International Research Fellowships (FIC)",
    "F30": "Individual Predoctoral NRSA for M.D./Ph.D. Fellowships",
    "F31": "Predoctoral Individual National Research Service Award",
    "F32": "Postdoctoral Individual National Research Service Award",
    "F33": "National Research Service Awards for Senior Fellows",
    "F37": "Medical Informatics Fellowships",
    "F38": "Applied Medical Informatics Fellowships",
    "F99": "Predoctoral to Postdoctoral Fellow Transition Award",
    "FI2": "Intramural Postdoctoral Research Associate",
    "FM1": "Fellowship for Intramural Dual-Degree Scientists (FIDDS)",
    "G07": "Resources Improvement Grant",
    "G08": "Resources Project Grant (NLM)",
    "G11": "Extramural Associate Research Development Award (EARDA)",
    "G12": "Research Centers in Minority Institutions Award",
    "G13": "Health Sciences Publication Support Awards (NLM)",
    "G20": "Grants for Repair, Renovation and Modernization of Existing Research Facilities",
    "G94": "Administrative Support for Public Health Service Agency Foundations",
    "H13": "Conferences Active",
    "H23": "Immunization Program",
    "H25": "Venereal Disease Control",
    "H28": "State and Community-Based Injury Control Programs",
    "H50": "Maternal and Child Health Services Project, RB Funds Active",
    "H57": "Indian Health Service Loan Repayment Program",
    "H62": "Services or Education on AIDS",
    "H64": "State and Community-Based Childhood Lead Poisoning Prevention Program",
    "H75": "Health Investigations/Assessments of Control/Preven. Methods",
    "H79": "Mental Health and/or Substance Abuse Services Grants",
    "HD4": "Drug Use/Alcohol Abuse Prevention Demo: Community Partnership Study",
    "I01": "Non-HHS Research Projects",
    "I80": "DoD Research Project Grant Program (I80)",
    "IK3": "Non-DHHS Nursing Research Initiative",
    "K00": "Post-doctoral Transition Award",
    "K01": "Research Scientist Development Award - Research & Training",
    "K02": "Research Scientist Development Award - Research",
    "K05": "Research Scientist Award",
    "K06": "Research Career Awards",
    "K07": "Academic/Teacher Award (ATA)",
    "K08": "Clinical Investigator Award (CIA)",
    "K12": "Physician Scientist Award (Program) (PSA)",
    "K14": "Resource-Limited Institution Faculty Development Awards",
    "K18": "The Career Enhancement Award",
    "K21": "Scientist Development Award",
    "K22": "Career Transition Award",
    "K23": "Mentored Patient-Oriented Research Career Development Award",
    "K24": "Midcareer Investigator Award in Patient-Oriented Research",
    "K25": "Mentored Quantitative Research Career Development Award",
    "K26": "Midcareer Investigator Award in Biomedical and Behavioral Research",
    "K30": "Clinical Research Curriculum Award (CRCA)",
    "K32": "Academic Career Excellence (ACE) Award",
    "K38": "Early Stage Mentored Research and Career Development",
    "K43": "International Research Career Development Award",
    "K76": "Emerging Leaders Career Development Award",
    "K99": "Career Transition Award",
    "KD1": "Mental Health and/or Substance Abuse KD&A Grants",
    "KL1": "Linked Research Career Development Award",
    "KL2": "Mentored Career Development Award",
    "KM1": "Institutional Career Enhancement Awards - Multi-Yr Funding",
    "L30": "Loan Repayment Program for Clinical Researchers",
    "L32": "Loan Repayment Program for Clinical Researchers from Disadvantaged Backgrounds",
    "L40": "Loan Repayment Program for Pediatric Research",
    "L50": "Loan Repayment Program for Contraception and Infertility Research",
    "L60": "Loan Repayment Program for Health Disparities Research",
    "L70": "Loan Repayment Program for Research in Emerging Areas Critical to Human Health",
    "M01": "General Clinical Research Centers Program",
    "OT2": "Research Project-Other Transaction Award",
    "P01": "Research Program Projects",
    "P20": "Exploratory Grants",
    "P2C": "Resource-Related Research Multi-Component Projects and Centers",
    "P30": "Center Core Grants",
    "P40": "Animal (Mammalian and Nonmammalian) Model, and Animal and Biological Material Resource Grants",
    "P41": "Biotechnology Resource Grants",
    "P42": "Hazardous Substances Basic Research Grants Program (NIEHS)",
    "P50": "Specialized Center",
    "P51": "Primate Research Center Grants",
    "P60": "Comprehensive Center",
    "PF5": "Collaborative International Research Project",
    "PL1": "Linked Center Core Grant",
    "PM1": "Program Project or Center with Complex Structure",
    "PN1": "Concept Development Award",
    "PN2": "Research Development Center",
    "R00": "Research Transition Award",
    "R01": "Research Project",
    "R03": "Small Research Grants",
    "R13": "Conference",
    "R15": "Research Enhancement Awards",
    "R16": "Research Excellence Award",
    "R18": "Research Demonstration and Dissemination Projects",
    "R21": "Exploratory/Developmental Grants",
    "R24": "Resource-Related Research Projects",
    "R25": "Education Projects",
    "R28": "Resource-Related Research Projects",
    "R2F": "Food Safety Capacity and Infrastructure Building",
    "R30": "Preventive Health Service - Venereal Disease Research, Demonstration, and Public Information and Education Grants",
    "R33": "Exploratory/Developmental Grants Phase II",
    "R34": "Planning Grant",
    "R35": "Investigator-Focused Award",
    "R36": "Dissertation Award",
    "R37": "Method to Extend Research in Time (MERIT) Award",
    "R38": "Mentored Research Pathway in Residency",
    "R41": "Small Business Technology Transfer (STTR) Grants - Phase I",
    "R42": "Small Business Technology Transfer (STTR) Grants - Phase II",
    "R43": "Small Business Innovation Research Grants (SBIR) - Phase I",
    "R44": "Small Business Innovation Research Grants (SBIR) - Phase II",
    "R49": "Injury Control Research and Demonstration Projects and Injury Prevention Research Centers",
    "R50": "Research Specialist Award",
    "R55": "James A. Shannon Director's Award",
    "R56": "High Priority, Short Term Project Award",
    "R61": "Phase 1 Exploratory/Developmental Grant",
    "R90": "Interdisciplinary Regular Research Training Award",
    "RC1": "NIH Challenge Grants and Partnerships Program",
    "RC2": "High Impact Research and Research Infrastructure Programs",
    "RC3": "Biomedical Research, Development, and Growth to Spur the Acceleration of New Technologies (BRDG-SPAN) Program",
    "RC4": "High Impact Research and Research Infrastructure Programs—Multi-Yr Funding",
    "RF1": "Multi-Year Funded Research Project Grant",
    "RF2": "Linked International Research Project",
    "RL1": "Linked Research project Grant",
    "RL2": "Linked Exploratory/Development Grant",
    "RL5": "Linked Education Project",
    "RL9": "Linked Research Training Award",
    "RM1": "Research Project with Complex Structure",
    "RP1": "Science-Driven Research Project",
    "RS1": "Programs to Prevent the Emergence and Spread of Antimicrobial Resistance in the United States",
    "S06": "Tribal Biomedical Research Support",
    "S07": "Biomedical Research Support Grants",
    "S10": "Biomedical Research Support Shared Instrumentation Grants",
    "S11": "Biomedical Research Support Thematic Project Grants for Developing Institutions",
    "S15": "Small Instrumentation Grants Program",
    "S21": "Research and Institutional Resources Health Disparities Endowment Grants -Capacity Building",
    "S22": "Research and Student Resources Health Disparities Endowment Grants - Educational Programs",
    "SB0": "Phase 0 Proof of Concept Partnership",
    "SB1": "Commercialization Readiness Program",
    "SC1": "Research Enhancement Award",
    "SC2": "Pilot Research Project",
    "SC3": "Research Continuance Award",
    "SI2": "Intramural Clinical Scholar Research Award",
    "T01": "Graduate Training Program",
    "T02": "Undergraduate Training Program",
    "T09": "Scientific Evaluation",
    "T14": "Conferences",
    "T15": "Continuing Education Training Grants",
    "T32": "Institutional National Research Service Award",
    "T34": "Undergraduate NRSA Institutional Research Training Grants",
    "T35": "NRSA Short-Term Research Training",
    "T37": "International Research Training Grants",
    "T42": "Educational Resource Center Training Grants",
    "T90": "Interdisciplinary Research Training Award",
    "TL1": "Linked Training Award",
    "TL4": "Undergraduate NRSA Institutional Research Training Grants",
    "TU2": "Institutional National Research Service Award with Involvement of NIH Intramural Faculty",
    "U01": "Research Project--Cooperative Agreements",
    "U09": "Scientific Review and Evaluation--Cooperative Agreements",
    "U10": "Cooperative Clinical Research--Cooperative Agreements",
    "U11": "Study (in China) of Periconceptional Vitamin Supplements to Prevent Spina Bifida and Anencephaly Cooperative Agreements",
    "U13": "Conference--Cooperative Agreements",
    "U17": "Applied Methods in Violence-Related or Accidental Injury Surveillance Cooperative Agreements",
    "U18": "Research Demonstration--Cooperative Agreements",
    "U19": "Research Program--Cooperative Agreements",
    "U1A": "Capacity Building for Core Components of Tobacco Prevention and Control Programs Cooperative Agreements",
    "U1B": "Cooperative Agreement for Research and Surveillance Activities to Reduce the Incidence of HIV/AIDS",
    "U1Q": "Emergency Disaster Relief Relating to CDC Programs Cooperative Agreement",
    "U1V": "Capacity Building for Core Components of Tobacco Prevention and Control Programs Cooperative Agreements",
    "U21": "Immunization Service Cooperative Agreements",
    "U22": "HIV/STD Preventive Services",
    "U23": "TB Prevention and Control Services Cooperative Agreements",
    "U24": "Resource-Related Research Projects--Cooperative Agreements",
    "U27": "Surveillance of Complications of Hemophilia Cooperative Agreements",
    "U2C": "Resource-Related Research Multi-Component Projects and Centers Cooperative Agreements",
    "U2F": "Food Safety Capacity and Infrastructure Building",
    "U2G": "Global HIV/AIDS Non-Research Cooperative Agreements",
    "U2R": "International Research Training Cooperative Agreements",
    "U30": "Prev. Health Services: Venereal Disease Research, Demonstration, and Public Information and Education Projects",
    "U32": "State-based Diabetes Control Programs",
    "U34": "Planning Cooperative Agreement",
    "U36": "Program Improvements for Schools of Public Health",
    "U38": "Uniform National Health Program Reporting System",
    "U3R": "NIH Small Research Grant Program (Cooperative Agreement)",
    "U41": "Biotechnology Resource Cooperative Agreements",
    "U42": "Animal (Mammalian and Nonmammalian) Model, and Animal and Biological Materials Resource Cooperative Agreements",
    "U43": "Small Business Innovation Research (SBIR) Cooperative Agreements - Phase I",
    "U44": "Small Business Innovation Research (SBIR) Cooperative Agreements  - Phase II",
    "U45": "Hazardous Waste Worker Health and Safety Training Cooperative Agreements (NIEHS)",
    "U47": "Laboratory/Other Diagnostic Medical Quality Improvement Cooperative Agreements",
    "U48": "Health Promotion and Disease Prevention Research Centers",
    "U49": "Coop: Injury Control Res. and Demo and Injury Prevention",
    "U50": "Special Cooperative Investigations/Assessment of Control/Prevention Methods",
    "U51": "Health Planning Strategies/National Academy of Sciences Activities",
    "U52": "Cooperative Agreement for Tuberculosis Control",
    "U53": "Capacity Bldg: Occupational Safety/Community Environmental Health",
    "U54": "Specialized Center--Cooperative Agreements",
    "U55": "Core Support For American Council on Transplantation Active",
    "U56": "Exploratory Grants--Cooperative Agreements",
    "U57": "State-Based Comprehensive Breast/Cervical Cancer Control Program Cooperative Agreements",
    "U58": "Chronic Disease Control Cooperative Agreement",
    "U59": "Disabilities Prevention Cooperative Agreement Program",
    "U60": "Cooperative Agreements in Occupational Safety and Health Research, Demonstrations, Evaluation and Education Research, Demonstrations, Evaluation and Education",
    "U61": "Preventive Health Activities Regarding Hazardous Substances",
    "U62": "Prevention/Surveillance Activities/Studies of AIDS",
    "U65": "Minority/Other Community-based HIV Prevention Project, Cooperative Agreements",
    "U66": "Immunization Demonstration Projects Cooperative Agreements",
    "U75": "National Cancer Registries Cooperative Agreements",
    "U79": "Mental Health and/or Substance Abuse Services Cooperative Agreements",
    "U81": "Injury Community Demonstration Projects: Evaluation of Youth Violence Prevention Program",
    "U82": "Enhancement of State and Local Capacity to Assess the Progress toward Healthy People 2010 Objectives",
    "U83": "Research to Advance the Understanding of the Health of Racial and Ethnic Populations or Subpopulations Cooperative Agreements",
    "U84": "Cooperative Agreements for Fetal Alcohol Syndrome Prevention Research Programs",
    "U86": "State Demonstration: Comprehensive School Health Programs to Prevent  Important Health Problems and Improve Educational Outcome",
    "U87": "State Demonstration:  Comprehensive School Health Program to Prevent Sexual Behaviors that Result in HIV Infection and to Improve Educational Outcome",
    "U90": "Cooperative Agreements for Special Projects of National Significance (SPNS)",
    "UA1": "AIDS Research Project Cooperative Agreement",
    "UA5": "Academic Research Enhancement Award (AREA) Cooperative Agreements",
    "UB1": "Commercialization Readiness Program – Cooperative Agreement",
    "UC1": "NIH Challenge Grants and Partnerships Program - Phase II-Coop.Agreement",
    "UC2": "High Impact Research and Research Infrastructure Cooperative Agreement Programs",
    "UC3": "Biomedical Research, Development, and Growth to Spur the Acceleration of New Technologies (BRDG-SPAN) Cooperative Agreement Program",
    "UC4": "High Impact Research and Research Infrastructure Cooperative Agreement Programs—Multi-Yr Funding",
    "UC6": "Construction Cooperative Agreement",
    "UC7": "Biocontainment Laboratory Operation Cooperative Agreement",
    "UD1": "Mental Health and/or Substance Abuse KD&A Cooperative Agreements",
    "UE1": "Studies of Environmental Hazards and Health Effects",
    "UE2": "Emergency and Environmental Health Services",
    "UE5": "Education Projects - Cooperative Agreements",
    "UF1": "Multi-Year Funded Research Project Cooperative Agreement",
    "UF2": "Rape Prevention and Education Cooperative Agreement",
    "UF5": "Collaborative International Cooperative Agreement",
    "UG1": "Clinical Research Cooperative Agreements - Single Project",
    "UG3": "Phase 1 Exploratory/Developmental Cooperative Agreement",
    "UG4": "National Network of Libraries of Medicine",
    "UH1": "HBCU Research Scientist Award",
    "UH2": "Exploratory/Developmental Cooperative Agreement Phase I",
    "UH3": "Exploratory/Developmental Cooperative Agreement Phase II",
    "UH4": "Hazmat Training at DOE Nuclear Weapons Complex",
    "UL1": "Linked Specialized Center Cooperative Agreement",
    "UL2": "Linked International Cooperative Agreement",
    "UM1": "Research Project with Complex Structure Cooperative Agreement",
    "UM2": "Program Project or Center with Complex Structure Cooperative Agreement",
    "UP1": "Science-Driven Research Project Cooperative Agreement",
    "UP5": "Early Independence Award Cooperative Agreement",
    "UR6": "Prevention Intervention Research on Substance Abuse in Children Cooperative Agreements",
    "UR8": "Applied Research in Emerging Infections-(including Tick-borne Diseases) Cooperative Agreements",
    "US3": "Hantaviral Reservoir Studies Cooperative Agreements",
    "US4": "Community-Based Primary Prevention Programs: Intimate Partner Violence Cooperative Agreements",
    "UT1": "Small Business Technology Transfer (STTR) – Cooperative Agreements - Phase I",
    "UT2": "Small Business Technology Transfer (STTR) – Cooperative Agreements - Phase II",
    "VF1": "Rape Prevention and Education Grants",
    "X01": "Resource Access Program",
    "X02": "Preapplication",
    "X98": "Protection and Advocacy for Mentally Ill Individuals",
    "X99": "National All Schedules Prescription Electronic Reporting (NASPER)",
}

# code -> NIH's "Funding Category" cell, verbatim. Not shown to students.
FUNDING_CATEGORY: Dict[str, str] = {
    "C06": "Construction and Modernization",
    "D43": "Research Training and Career Development",
    "D71": "Research Training and Career Development",
    "DP1": "Research and Development",
    "DP2": "Research and Development",
    "DP3": "Research and Development",
    "DP4": "Research and Development",
    "DP5": "Research and Development",
    "DP7": "Research Training and Career Development",
    "F05": "Research Training and Career Development",
    "F30": "Research Training and Career Development",
    "F31": "Research Training and Career Development",
    "F32": "Research Training and Career Development",
    "F33": "Research Training and Career Development",
    "F37": "Research Training and Career Development",
    "F38": "Research Training and Career Development",
    "F99": "Research Training and Career Development",
    "FI2": "Research Training and Career Development",
    "FM1": "Research Training and Career Development",
    "G07": "Research and Development",
    "G08": "Research and Development",
    "G11": "Research and Development",
    "G13": "Research and Development",
    "G20": "Construction and Modernization",
    "I01": "Research and Development",
    "I80": "Research and Development",
    "IK3": "Research Training and Career Development",
    "K00": "Research Training and Career Development",
    "K01": "Research Training and Career Development",
    "K02": "Research Training and Career Development",
    "K05": "Research Training and Career Development",
    "K06": "Research Training and Career Development",
    "K07": "Research Training and Career Development",
    "K08": "Research Training and Career Development",
    "K12": "Research Training and Career Development",
    "K14": "Research Training and Career Development",
    "K18": "Research Training and Career Development",
    "K21": "Research Training and Career Development",
    "K22": "Research Training and Career Development",
    "K23": "Research Training and Career Development",
    "K24": "Research Training and Career Development",
    "K25": "Research Training and Career Development",
    "K26": "Research Training and Career Development",
    "K30": "Research Training and Career Development",
    "K32": "Research Training and Career Development",
    "K38": "Research Training and Career Development",
    "K43": "Research Training and Career Development",
    "K76": "Research Training and Career Development",
    "K99": "Research Training and Career Development",
    "KD1": "Research Training and Career Development",
    "KL1": "Research Training and Career Development",
    "KL2": "Research Training and Career Development",
    "KM1": "Research Training and Career Development",
    "L30": "Loan Repayment Programs",
    "L32": "Loan Repayment Programs",
    "L40": "Loan Repayment Programs",
    "L50": "Loan Repayment Programs",
    "L60": "Loan Repayment Programs",
    "L70": "Loan Repayment Programs",
    "OT2": "Other Transactions",
    "P01": "Research and Development",
    "P20": "Research and Development",
    "P2C": "Research and Development",
    "P30": "Research and Development",
    "P40": "Research and Development",
    "P41": "Research and Development",
    "P42": "Research and Development",
    "P50": "Research and Development",
    "P51": "Research and Development",
    "P60": "Research and Development",
    "PL1": "Research and Development",
    "PM1": "Research and Development",
    "PN1": "Research and Development",
    "PN2": "Research and Development",
    "R00": "Research and Development",
    "R01": "Research and Development",
    "R03": "Research and Development",
    "R13": "Research and Development",
    "R15": "Research and Development",
    "R16": "Research and Development",
    "R18": "Research and Development",
    "R21": "Research and Development",
    "R24": "Research and Development",
    "R25": "Research Training and Career Development",
    "R28": "Research and Development",
    "R33": "Research and Development",
    "R34": "Research and Development",
    "R35": "Research and Development",
    "R36": "Research Training and Career Development",
    "R37": "Research and Development",
    "R38": "Research Training and Career Development",
    "R41": "Small Business",
    "R42": "Small Business",
    "R43": "Small Business",
    "R44": "Small Business",
    "R50": "Research and Development",
    "R55": "Research and Development",
    "R56": "Research and Development",
    "R61": "Research and Development",
    "R90": "Research Training and Career Development",
    "RC1": "Research and Development",
    "RC2": "Research and Development",
    "RC3": "Research and Development",
    "RC4": "Research and Development",
    "RF1": "Research and Development",
    "RL1": "Research and Development",
    "RL2": "Research and Development",
    "RL5": "Research Training and Career Development",
    "RL9": "Research Training and Career Development",
    "RM1": "Research and Development",
    "RP1": "Research and Development",
    "RS1": "Research and Development",
    "S06": "Research and Development",
    "S07": "Research and Development",
    "S10": "Research and Development",
    "S11": "Research and Development",
    "S15": "Research and Development",
    "S21": "Research and Development",
    "S22": "Research Training and Career Development",
    "SB0": "Research and Development,Small Business",
    "SB1": "Small Business",
    "SC1": "Research and Development",
    "SC2": "Research and Development",
    "SC3": "Research and Development",
    "SI2": "Research and Development",
    "T01": "Research Training and Career Development",
    "T02": "Research Training and Career Development",
    "T09": "Research Training and Career Development",
    "T14": "Research Training and Career Development",
    "T15": "Research Training and Career Development",
    "T32": "Research Training and Career Development",
    "T34": "Research Training and Career Development",
    "T35": "Research Training and Career Development",
    "T37": "Research Training and Career Development",
    "T42": "Research Training and Career Development",
    "T90": "Research Training and Career Development",
    "TL1": "Research Training and Career Development",
    "TL4": "Research Training and Career Development",
    "TU2": "Research Training and Career Development",
    "U01": "Research and Development",
    "U13": "Research and Development",
    "U19": "Research and Development",
    "U24": "Research and Development",
    "U2F": "Research and Development",
    "U2R": "Research Training and Career Development",
    "U34": "Research and Development",
    "U3R": "Research and Development",
    "U43": "Small Business",
    "U44": "Small Business",
    "U54": "Research and Development",
    "UA5": "Research and Development",
    "UB1": "Small Business",
    "UC2": "Research and Development",
    "UC6": "Construction and Modernization",
    "UE5": "Research Training and Career Development",
    "UF1": "Research and Development",
    "UG3": "Research and Development",
    "UH2": "Research and Development",
    "UH3": "Research and Development",
    "UM1": "Research and Development",
    "UM2": "Research and Development",
    "UP1": "Research and Development",
    "UP5": "Research Training and Career Development",
    "UT1": "Small Business",
    "UT2": "Small Business",
    "X01": "Research and Development",
}


def normalise_code(code) -> Optional[str]:
    """Trimmed and upper-cased; None for a blank or a non-string.

    RePORTER sends the code upper-case already. Normalising here means a stray space or
    a lower-case value from a hand-built row still matches, while a number or a dict
    (a malformed record) is refused instead of being stringified into a false match.
    """
    if not isinstance(code, str):
        return None
    cleaned = code.strip().upper()
    return cleaned or None


def official_name(code) -> Optional[str]:
    """NIH's published name for the code, or None when the code is not in the snapshot.

    Never a guess: an unknown code returns None so the card can say nothing rather than
    print a plausible name NIH did not publish.
    """
    key = normalise_code(code)
    if key is None:
        return None
    return OFFICIAL_NAMES.get(key)


def is_known(code) -> bool:
    return official_name(code) is not None
